In [2]:
import torch

In [ ]:
x = torch.arange(12)
print(x)
x.shape
x.numel()  #标量

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


12

In [7]:
x1 = x.reshape((3, 4))
x1

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
print(torch.zeros((2, 3, 4)))
print(torch.ones((1, 2, 3)))
print(torch.tensor([[2, 1, 4, 3], [0, 0, 0, 0]]))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.]]])
tensor([[2, 1, 4, 3],
        [0, 0, 0, 0]])


In [14]:
a = torch.zeros((2, 3, 4))
b = torch.ones((2, 3, 4))
a + b, a - b, a * b, a / b,
torch.cat((a, b), dim = 0), torch.cat((a, b), dim = 1)

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [15]:
x = torch.arange(12)
x.sum()

tensor(66)

#### 广播机制  
形状不同，仍然可以扩展成形状相同的进行按元素计算

In [16]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b, a + b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [19]:
x = x.reshape((3, 4))
x[-1]

tensor([ 8,  9, 10, 11])

#### 访问

#### 内存问题  
用+= 或者切片访问 来避免新的内存分配

NumPy 张量 标量的转换

In [33]:
x = torch.arange(24).reshape((1, 2, 3, 4))
x.numpy(), torch.tensor(x.numpy()), x.sum().item()

(array([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]]),
 tensor([[[[ 0,  1,  2,  3],
           [ 4,  5,  6,  7],
           [ 8,  9, 10, 11]],
 
          [[12, 13, 14, 15],
           [16, 17, 18, 19],
           [20, 21, 22, 23]]]]),
 276)

## 数据预处理

In [ ]:
import os
os.makedirs(os.path.join('..', 'data'), exist_ok=True)

In [ ]:
data_file = os.path.join('..', 'data', 'house_white.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,P,12\n')
    f.write('2,NA,10\n')
    f.write('4,NA,10\n')
    f.write('NA,NA,20\n')

In [ ]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley  Price
0       NaN     P     12
1       2.0   NaN     10
2       4.0   NaN     10
3       NaN   NaN     20


#### NA变成均值

In [ ]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

   NumRooms Alley
0       3.0     P
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


#### 视作类别

In [ ]:
inputs = pd.get_dummies(inputs, dummy_na=True, dtype=int)
print(inputs)

   NumRooms  Alley_P  Alley_nan
0       3.0        1          0
1       2.0        0          1
2       4.0        0          1
3       3.0        0          1


In [ ]:
import torch

x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([12, 10, 10, 20]))