## 自动求导：计算图
[note](/home/sucrosato/work/code/LearningDeepLearning/pytorch/chapter_preliminaries/autograd.ipynb)  
显式构造、隐式构造  

正向存储值，反向利用值来计算


In [23]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [24]:
x.requires_grad_(True)
x.grad

In [25]:
y = 2 * torch.dot(x, x)
y

y.backward()
x.grad, x.grad == 4 * x

(tensor([ 0.,  4.,  8., 12.]), tensor([True, True, True, True]))

In [28]:
# x.grad.zero_()  #清零
y = x.sum()
y.backward()
x.grad

tensor([3., 3., 3., 3.])

In [ ]:
x.grad.zero_()
y = x * x 
y
y.sum().backward()    #对向量求导需要特殊处理
x.grad

tensor([0., 2., 4., 6.])

In [31]:
x.grad.zero_()
y = x * x
u = y.detach()    #视作常数
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])