矩阵的范数
1. 最小满足
$$||c|| \leq ||A|| \cdot ||b||$$
的值

2. Frobenius：平方相加  

置换矩阵？  
特征向量：不被矩阵改变方向的向量

In [2]:
import torch
A = torch.arange(12).reshape((3, 4))
A, A.T

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]]))

In [3]:
B = A.clone()
B[0][0] = 12
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
sum_A = A.sum(axis = -1, keepdim=True) #按轴求和、keepdim方便广播
A, sum_A, A / sum_A


(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 6],
         [22],
         [38]]),
 tensor([[0.0000, 0.1667, 0.3333, 0.5000],
         [0.1818, 0.2273, 0.2727, 0.3182],
         [0.2105, 0.2368, 0.2632, 0.2895]]))

In [ ]:
A, A.cumsum(axis=0), A.cumsum(axis=1) #累加求和，或前缀和

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  6,  8, 10],
         [12, 15, 18, 21]]),
 tensor([[ 0,  1,  3,  6],
         [ 4,  9, 15, 22],
         [ 8, 17, 27, 38]]))

点积

In [21]:
x = y = torch.arange(4)
torch.dot(x, y), torch.sum(x * y)

(tensor(14), tensor(14))

矩阵乘法

In [28]:
A = torch.arange(12).reshape((3, 4))
x = torch.arange(4)
torch.mv(A, x)   #matrix-vector multiplication
B = torch.ones((4, 5), dtype=int)
torch.mm(A, B)   #matmul

tensor([[ 6,  6,  6,  6,  6],
        [22, 22, 22, 22, 22],
        [38, 38, 38, 38, 38]])

范数

In [41]:
a = torch.norm(x.float()) ** 2  #L2范数
b = torch.abs(x).sum()   #L1范数
c = torch.norm(torch.ones((7, 7)))   #矩阵Frobenius范数
a, b, c

(tensor(14.0000), tensor(6), tensor(7.))